microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/doPayment1
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/placeOrder
